import Mathlib.Data.Complex.Basic
import Mathlib.Data.Matrix.ColumnRowPartitioned
import Mathlib.LinearAlgebra.Matrix.ConjTranspose
import Mathlib.LinearAlgebra.Matrix.NonsingularInverse
import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.Tactic.Ring

/-!
# Order-six complex Hadamard matrices

This file fixes the matrix model used by the formal audit.  We index an
order-six matrix by `Fin 3 ⊕ Fin 3`, so that its four `3 x 3` blocks are
literal `Matrix.fromBlocks` blocks.
-/

namespace Hadamard6

abbrev I3 := Fin 3
abbrev I6 := I3 ⊕ I3
abbrev I2 := Fin 2
abbrev Mat2 := Matrix I2 I2 ℂ
abbrev Mat3 := Matrix I3 I3 ℂ
abbrev Mat6 := Matrix I6 I6 ℂ

/-- Every entry of `A` lies on the complex unit circle. -/
def EntrywiseUnit {m n : Type} (A : Matrix m n ℂ) : Prop :=
  ∀ i j, Complex.normSq (A i j) = 1

/-- The square complex Hadamard condition in order six. -/
def IsHadamard (H : Mat6) : Prop :=
  EntrywiseUnit H ∧
    H * Matrix.conjTranspose H = (6 : ℂ) • (1 : Mat6)

def IsHadamard3 (H : Mat3) : Prop :=
  EntrywiseUnit H ∧
    H * Matrix.conjTranspose H = (3 : ℂ) • (1 : Mat3)

def IsHadamard2 (H : Mat2) : Prop :=
  EntrywiseUnit H ∧
    H * Matrix.conjTranspose H = (2 : ℂ) • (1 : Mat2)

/-- A direct description of the usual row/column equivalence relation:
permutations followed by multiplication of rows and columns by phases. -/
def Equivalent (H K : Mat6) : Prop :=
  ∃ (σ τ : Equiv.Perm I6) (r c : I6 → ℂ),
    (∀ i, Complex.normSq (r i) = 1) ∧
    (∀ j, Complex.normSq (c j) = 1) ∧
    ∀ i j, K i j = r i * H (σ i) (τ j) * c j

/-- The dephased four-phase corner used in the paper. -/
def corner (a b c d : ℂ) : Mat3 :=
  !![1, 1, 1;
     1, a, b;
     1, c, d]

/-- Four unit phases specifying a dephased corner. -/
structure CornerData where
  a : ℂ
  b : ℂ
  c : ℂ
  d : ℂ
  abs_a : Complex.normSq a = 1
  abs_b : Complex.normSq b = 1
  abs_c : Complex.normSq c = 1
  abs_d : Complex.normSq d = 1

def CornerData.matrix (p : CornerData) : Mat3 :=
  corner p.a p.b p.c p.d

theorem equivalent_refl (H : Mat6) : Equivalent H H := by
  refine ⟨Equiv.refl I6, Equiv.refl I6, (fun _ ↦ 1), (fun _ ↦ 1), ?_, ?_, ?_⟩
  · intro i
    simp
  · intro j
    simp
  · intro i j
    simp

theorem star_mul_self_of_normSq_one {z : ℂ}
    (hz : Complex.normSq z = 1) : star z * z = 1 := by
  simpa [Complex.star_def, Complex.normSq_eq_conj_mul_self] using
    congrArg (fun a : ℝ ↦ (a : ℂ)) hz

theorem equivalent_trans {H K L : Mat6}
    (hHK : Equivalent H K) (hKL : Equivalent K L) : Equivalent H L := by
  rcases hHK with ⟨σ₁, τ₁, r₁, c₁, hr₁, hc₁, hHK⟩
  rcases hKL with ⟨σ₂, τ₂, r₂, c₂, hr₂, hc₂, hKL⟩
  refine ⟨σ₂.trans σ₁, τ₂.trans τ₁,
    (fun i ↦ r₂ i * r₁ (σ₂ i)),
    (fun j ↦ c₁ (τ₂ j) * c₂ j), ?_, ?_, ?_⟩
  · intro i
    simp [Complex.normSq_mul, hr₂ i, hr₁ (σ₂ i)]
  · intro j
    simp [Complex.normSq_mul, hc₁ (τ₂ j), hc₂ j]
  · intro i j
    rw [hKL, hHK]
    simp only [Equiv.trans_apply]
    ring

/-- Hadamard equivalence is symmetric.  The inverse transformation uses the
inverse permutations and the conjugates of the row and column phases. -/
theorem equivalent_symm {H K : Mat6} (hHK : Equivalent H K) :
    Equivalent K H := by
  rcases hHK with ⟨σ, τ, r, c, hr, hc, hHK⟩
  refine ⟨σ.symm, τ.symm,
    (fun i ↦ star (r (σ.symm i))),
    (fun j ↦ star (c (τ.symm j))), ?_, ?_, ?_⟩
  · intro i
    simpa [Complex.normSq_conj] using hr (σ.symm i)
  · intro j
    simpa [Complex.normSq_conj] using hc (τ.symm j)
  · intro i j
    have h := hHK (σ.symm i) (τ.symm j)
    simp only [Equiv.apply_symm_apply] at h ⊢
    have hri : star (r (σ.symm i)) * r (σ.symm i) = 1 :=
      star_mul_self_of_normSq_one (hr (σ.symm i))
    have hcj : c (τ.symm j) * star (c (τ.symm j)) = 1 := by
      simpa [mul_comm] using
        star_mul_self_of_normSq_one (hc (τ.symm j))
    rw [h]
    symm
    calc
      star (r (σ.symm i)) *
          (r (σ.symm i) * H i j * c (τ.symm j)) *
          star (c (τ.symm j)) =
        (star (r (σ.symm i)) * r (σ.symm i)) * H i j *
          (c (τ.symm j) * star (c (τ.symm j))) := by ring
      _ = H i j := by rw [hri, hcj]; simp

/-- `Equivalent` is the equivalence relation generated by row/column
permutations and unit row/column phases. -/
theorem equivalent_equivalence : Equivalence Equivalent :=
  ⟨equivalent_refl, equivalent_symm, equivalent_trans⟩

/-- The setoid used later to form equivalence classes of order-six
matrices. -/
def matrixEquivalenceSetoid : Setoid Mat6 where
  r := Equivalent
  iseqv := equivalent_equivalence

theorem cornerData_entrywiseUnit (p : CornerData) :
    EntrywiseUnit p.matrix := by
  intro i j
  fin_cases i <;> fin_cases j <;>
    simp [CornerData.matrix, corner, p.abs_a, p.abs_b, p.abs_c, p.abs_d]

theorem cornerData_firstRow (p : CornerData) (j : I3) :
    p.matrix 0 j = 1 := by
  fin_cases j <;> simp [CornerData.matrix, corner]

theorem cornerData_firstColumn (p : CornerData) (i : I3) :
    p.matrix i 0 = 1 := by
  fin_cases i <;> simp [CornerData.matrix, corner]

end Hadamard6
